name: Client - Build and test

on:
  push:
    branches-ignore:
      - main
      - release*
    paths:
      - client/**
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      working-directory: ./client

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: '12'
      - run: npm install
        working-directory: ${{ env.working-directory }}
      - run: npm test
        working-directory: ${{ env.working-directory }}