name: Server - Deploy

on:
  push:
    branches:
      - main
    paths:
      - server/**

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO_SERVER }}
      working-directory: ./server

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ${{ env.working-directory }}/Dockerfile
          push: true
          tags: ${{ env.REPO }}:latest

  update:
    name: Update service using webhooks
    runs-on: ubuntu-latest
    needs: [ docker ]
    environment:
      name: server production
      url: https://vc.radiationservers.com/
    steps:
      - name: Run curl POST request
        run: curl -X POST ${{ secrets.WEBHOOK_BACKEND }}