name: Build Docker Image Python Backend

on:
  push:
    branches: [ main ]
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jellehuibregtse/vertex-cover-backend:latest

  update:
    name: Update service using webhooks
    runs-on: ubuntu-latest
    needs: [ docker ]
    environment:
        name: production
        url: https://vc.radiationservers.com/
    steps:
      - name: Run curl POST request
        run: curl -X POST ${{ secrets.WEBHOOK_BACKEND }}